# @name get-prompts

GET http://localhost:3333/prompts

###

# @name upload

POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="decha.mp3"
Content-Type: audio/mpeg

< ./decha.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription

POST http://localhost:3333/videos/d6c0736d-5715-4324-addf-696079a78914/transcription
Content-Type: application/json

{
    "prompt": "desenvolvedor junior, conselhos"
}

###

# @name generate-ai

POST http://localhost:3333/ai/complete
Content-Type: application/json

{
    "videoId": "d6c0736d-5715-4324-addf-696079a78914",
    "temperature": 0.5,
    "prompt": "Gere um resumo sucinto da transcrisao do video informada a seguir:'''{transcription}''' "
}